/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.miracle.ai.seahorse.agent.adapters.repository.jdbc;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.miracle.ai.seahorse.agent.kernel.domain.stream.StreamEventEnvelope;
import com.miracle.ai.seahorse.agent.kernel.domain.stream.StreamEventType;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

class JdbcAgentRunEventBufferAdapterTests {

    @Test
    void shouldAppendAndReplayStructuredPayloadsInSequenceOrder() {
        DriverManagerDataSource dataSource = dataSource("agent-run-event-buffer-structured");
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
        createEventBufferSchema(jdbcTemplate);
        JdbcAgentRunEventBufferAdapter adapter = new JdbcAgentRunEventBufferAdapter(dataSource, new ObjectMapper());

        adapter.append("run-1", StreamEventEnvelope.of(2, StreamEventType.STEP_STARTED, "run-1",
                Map.of("stepId", "step-2")));
        adapter.append("run-1", StreamEventEnvelope.of(1, StreamEventType.RUN_STARTED, "run-1",
                Map.of("runId", "run-1")));
        adapter.append("run-2", StreamEventEnvelope.of(1, StreamEventType.RUN_STARTED, "run-2",
                Map.of("runId", "run-2")));

        List<StreamEventEnvelope> events = adapter.getAfter("run-1", 0);

        assertThat(events).extracting(StreamEventEnvelope::eventSeq).containsExactly(1L, 2L);
        assertThat(events).extracting(StreamEventEnvelope::runId).containsOnly("run-1");
        assertThat(adapter.getLatestSeq("run-1")).contains(2L);
    }

    @Test
    void shouldStorePlainStringPayloadAsJsonStringForReplay() {
        DriverManagerDataSource dataSource = dataSource("agent-run-event-buffer-string");
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
        createEventBufferSchema(jdbcTemplate);
        JdbcAgentRunEventBufferAdapter adapter = new JdbcAgentRunEventBufferAdapter(dataSource, new ObjectMapper());

        adapter.append("run-1", StreamEventEnvelope.of(1, StreamEventType.MESSAGE, "run-1", "{\"text\":\"hello\"}"));

        List<StreamEventEnvelope> events = adapter.getAfter("run-1", 0);

        assertThat(events).hasSize(1);
        assertThat(events.get(0).typedPayload()).isEqualTo("{\"text\":\"hello\"}");
    }

    private DriverManagerDataSource dataSource(String name) {
        return new DriverManagerDataSource(
                "jdbc:h2:mem:" + name + "-" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
    }

    private static void createEventBufferSchema(JdbcTemplate jdbcTemplate) {
        jdbcTemplate.execute("""
                CREATE TABLE sa_agent_run_event_buffer (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    run_id VARCHAR(64) NOT NULL,
                    event_seq BIGINT NOT NULL,
                    event_id VARCHAR(64) NOT NULL,
                    event_type VARCHAR(64) NOT NULL,
                    step_id VARCHAR(64),
                    payload JSON NOT NULL DEFAULT '{}',
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(run_id, event_seq)
                )
                """);
        jdbcTemplate.execute("""
                CREATE INDEX idx_sa_event_buffer_run_seq
                ON sa_agent_run_event_buffer(run_id, event_seq)
                """);
    }
}
